# Use postgres/example user/password credentials
version: '3.9'

services:
  postgres:
    image: chienesdt/postgresql_clone
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres_db